#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'
require 'infinum_setup'
require 'pry' if InfinumSetup.dev?

program :name, 'infinum_setup'
program :version, '0.0.1'
program :description, 'Setup infinum laptops'

default_command :install

command :install do |c|
  c.syntax = 'infinum_setup'
  c.description = 'Setups your laptop'
  c.option '-i', '--interactive', 'For expierienced users'
  c.option '-V', '--verbose', 'Print out commands'
  c.option '-s', '--simulate', 'Try before you buy'
  c.action do |_args, options|
    options.team = InfinumSetup::Install.select_team
    InfinumSetup::Install.new(options).call
  end
end
