#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'
require 'infinum_setup'

program :name, 'infinum_setup'
program :version, '0.0.1'
program :description, 'Setup infinum laptops'

default_command :install

command :install do |c|
  c.syntax = 'infinum_setup install'
  c.description = 'Setups your laptop'
  c.option '-i', '--interactive', 'For expierienced users'
  c.action do |_args, options|
    InfinumSetup::Install.new(options).call
  end
end
